# Site settings
title: A wonderful Montessori preschool - American Montessori School
email: info@americanmontessorischools.com
description: "A Montessori preschool that instills a lifelong joy of learning, serving Hillsborough, Bridgewater, Somerset NJ communities"
keywords: "Preschool, Hillsborough, Bridgewater, Belle Mead, Montgomery, Raritan, Somerset, montessori, daycares, kindergarten, private school"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.americanmontessorischools.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Google services
google_analytics: UA-65933630-1

# Build settings
markdown: kramdown

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
